[format]
align_predicates = true
align_prefixes = true
separate_prologue = false
capitalize_keywords = true
insert_spaces = true
tab_size = 2
where_new_line = true
filter_same_line = false 

[completion]
timeout_ms = 5000
result_size_limit = 100

[prefixes]
add_missing = true
remove_unused = false

[backends.codex-kg]
backend = { 
  name = "codex-kg",
  url = "http://codex.services.guc3.spotify.net:3330/spotify/query" 
  health_check_url = "http://codex.services.guc3.spotify.net:3330/ontology" 
}
prefixMap = { sp = "http://spotify.com/ontology#" }
